Repository gobuffalo/pop, pull requests merged in 2022-09, with the labels that each got.

#686 log SQL for association query
  executors.go
Labels: bug, s: accepted

#769 added test cases for slices.Map (for #655)
  slices/map_test.go
Labels: internal cleanup

#775 catch panic within transaction to complete rollback (fixes #748)
  connection.go
  connection_test.go
Labels: bug, security

#779 fixed replacing bug on WHERE IN statement (fixes #778)
  query.go
  query_test.go
Labels: bug

#780 fix missing Where in eager creation method
  executors.go
Labels: bug, associations

#776 removed mysqldump option `--column-statistics` to make it compatible with 5.7
  .github/workflows/tests.yml
  dialect_mysql.go
Labels: bug

#781 fix Connection.Close() to reset the store
  connection.go
  connection_test.go
Labels: bug

#782 made default logger to print output to stderr instead of stdout
  config.go
  logger.go
Labels: enhancement

#783 made the 'version' column primary key to fix #659
  schema_migrations.go
Labels: enhancement

#784 fixed delete + where in issue on mysql (#699)
  dialect_mysql.go
  query_test.go
Labels: bug, f: sql

#785 fixed concurrent map write issue on ConnectionDetails.Options (#577)
  connection_details.go
  dialect_cockroach.go
  dialect_mysql.go
  dialect_postgresql.go
  dialect_sqlite.go
Labels: bug

#786 prevent empty query to be executed
  executors.go
  query.go
  query_test.go
  sql_builder.go
Labels: bug

#787 updated README, SHOULDERS, and module dependencies
  README.md
  SHOULDERS.md
  go.mod
  go.sum
Labels: internal cleanup, process
